import Database from "better-sqlite3";
const db = new Database("database.db");

db.exec(`CREATE TABLE IF NOT EXISTS memories (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    username TEXT,
    message TEXT,
    date INTEGER,
    location TEXT,
    picture TEXT
)`);
db.exec(`INSERT into memories (username, message, date, location, picture)
VALUES
('TOM', 'HELLO', 5, 'norwich', 'https://posters.movieposterdb.com/22_10/2004/410519/l_the-matrix-recalibrated-movie-poster_74175b37.jpg'),
('afrobel', 'Amidst the solitude of the lockdown, confined to the walls of my home, a decision sparked a new chapter of joy. Longing for companionship, I embarked on a journey to adopt a German Shepherd puppy. The virtual adoption process brought anticipation, and soon, a furry ball of energy entered my life. Days turned into a delightful routine of training sessions, playful antics, and heartfelt moments. My once quiet home now echoed with the pitter-patter of puppy paws, filling the lockdown with warmth and unconditional love, turning an isolated period into an unexpected blessing.', 62224, 'Norwich', 'https://media.discordapp.net/attachments/1202977696636739615/1204377911117873213/image1.jpg?ex=65d48356&is=65c20e56&hm=0aa184e5f7815468611a004be4f95336c6262be41aa9791a07dae4b92482e88c&=&format=webp&width=536&height=518'),
('NotAtHome', 'Over lockdown we had a barbecue in our household in our garden and our neighbour decided it would be a good idea to spray a pressure washer over the wall at us and get us soaked without saying anything to us, because he was upset about the smoke coming from the BBQ. Then he proceeded to come round and punch a hole in our front door.. fun times', 124, 'unknown', 'picture'),
('scoobysnacks', 'Over lockdown I challenged myself to run 5k every day for thirty days and see how my fitness was at the end of it. I found it a struggle to be constantly running and found that my knee was in pain but that actually the experience was good in getting myself out of the house and active, and when I pushed myself to try and run faster - it worked! I managed to beat my 5k PB by some distance. I think it also helped that the weather was really nice over this period. If Im honest I probably wouldnt do it again because its good to give the body some rest, but I enjoyed it over the covid period.', 6224, 'Nottingham', 'https://images.unsplash.com/photo-1594882645126-14020914d58d?q=80&w=1485&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D'),
('PoisionIvy', 'I became addicted to houseplants and spent forty quid on a massive red imperial philodendron that was too big for my kitchen, I called her Pamela and she died on me 2 weeks later. I think my house was too cold. My best friend was very smart and captilised on the houseplant lockdown market and set up an online Etsy shop shipping plants all over the UK. I am very proud of her. ', 06/02/2024, 'Norfolk', 'https://plus.unsplash.com/premium_photo-1678812165213-12dc8d1f3e19?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8cGFpbnRpbmd8ZW58MHx8MHx8fDA%3D'),
('HappyLittleTrees', 'I taught myself to watercolour paint and bought too many sweets in bulk from Amazon. I can no longer look at white chocolate mice and not feel sick lol. I also attempted yoga for the first time..one of my cats tried to join in and I fell over. I did not try yoga again.', 524, 'unknown', 'picture'),
('EllieTheElephant', 'During the lockdown, my family decided to have a virtual game night with our relatives who lived in different cities. We set up a video call and started playing a game of charades.Everything was going smoothly until it was my turn to act out a word. I drew a card and saw the word elephant. Determined to impress everyone with my acting skills, I started miming a trunk swinging from side to side and making elephant noises. However, as I got into character, I accidentally knocked over a lamp with my flailing arms. The lamp crashed to the ground, and everyone on the video call erupted into laughter. It was a reminder that even though we were physically apart, we could still create hilarious memories and have fun together during lockdown, even if it meant breaking a few lamps in the process!', 624, 'unknown', 'picture'),
('sadMan', 'I had a great idea during covid to binge watch deal or no deal because Noel Edmunds is my hero. I mustve spent twenty hours out of a 24 hour period watching deal or no deal and quite honestly it may be one of the best days of my life. Noel Edmunds is a legend, I also enjoyed his work with Mr Blobby', 14124, 'unknown', 'https://images.unsplash.com/photo-1512373586232-4d7bb652fc62?q=80&w=1470&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D')`);
